### ISSUE TITLE
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions

### ISSUE THREAD

**Issue by miaowm5** [s4afa451dgf415f/colab_stable_diffusion#45]
运行到最后一步报错跳出了

```
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.2.1+cu121)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
*** Error setting up CodeFormer
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/codeformer_model.py", line 30, in setup_model
        from modules.codeformer.codeformer_arch import CodeFormer
      File "/content/stable-diffusion-webui/modules/codeformer/codeformer_arch.py", line 9, in <module>
        from modules.codeformer.vqgan_arch import VQAutoEncoder, ResBlock
      File "/content/stable-diffusion-webui/modules/codeformer/vqgan_arch.py", line 11, in <module>
        from basicsr.utils import get_root_logger
      File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
        from .data import *
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
        from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
        from torchvision.transforms.functional_tensor import rgb_to_grayscale
    ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

---
```

**Comment by s4afa451dgf415f** [comment]
我没pro,兄弟你再看看还能不能用。谷歌更新了torch的版本导致xformers没有相应的版本与sd兼容，目前只能覆盖安装torch，将花费1-2分钟更多的时间，之后我会寻找解决方案

**Comment by miaowm5** [comment]
感谢，可以用了
